### ISSUE TITLE
Updating to 2022

### ISSUE THREAD

**Issue by TheMathNinja** [dfs-with-r/ffespn#14]
Hi could you please update this package for 2022 leagues? This is my go-to for running multiple leagues! Thanks again. If you want a league code to use, this is the new one: 134971153

Thanks again so much for this package!

**Comment by zamorarr** [comment]
Hey there. I'm trying to figure out why this is not working. Where did you get that league id from?

**Comment by zamorarr** [comment]
I've tried updating the url. Can you try to reinstall and try again?

**Comment by TheMathNinja** [comment]
Thanks, this fixed the API issue!

I'm getting the league ID from the league I set up this year with all possible ESPN positions. Did you change the league ID by chance? I'm asking because I'm getting:

```
espndtproj2022 <- ffespn_projections(2022, 0, "DT")
Error: results are empty. no players found
```
Additionally, I'm getting error messages on offense:
```
espnqbproj2022 <- ffespn_projections(2022, 0, "QB")
Error in `vec_assign()`:
! Can't convert `replace` <character> to match type of `data` <list>.
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by TheMathNinja** [comment]
Thanks for your work on this, btw. Lmk where I might be able to donate.

**Comment by TheMathNinja** [comment]
I just changed the league setting to "Make League Viewable to the Public" in case that was causing the issue?

**Comment by zamorarr** [comment]
You know what, I bet that's it. I couldn't find the league last nigh probably because it wasn't public. I did change the league id back to the ESPN defaults so I'll switch it back to yours again this morning. 

If you don't want to wait for me to do it feel free to submit another pull request I can accept it.

Ideally I'd find the right endpoint for the ESPN default league with all positions, but I haven't been able to do it.

**Comment by zamorarr** [comment]
Fixed! Although I decided to allow anyone to input a custom league id instead of hard coding it in. You''ll have to do this now:

```r
my_id <- "134971153"
qb <- ffespn_projections(2022, 0, "QB", league_id = my_id)
dt <- ffespn_projections(2022, 0, "DT", league_id = my_id)

# and so on
```

Or if you just want to use the ESPN defaults any of these will work:
```r
qb <- ffespn_projections(2022, 0, "QB") # uses ppr by default
qb <- ffespn_projections(2022, 0, "QB", scoring = "ppr")
qb <- ffespn_projections(2022, 0, "QB", scoring = "non_ppr")
```

**Comment by TheMathNinja** [comment]
Thanks! However, I'm still getting this bug:

```
Error in `vec_assign()`:
! Can't convert `replace` <character> to match type of `data` <list>.
Run `rlang::last_error()` to see where the error occurred.
```

Are you seeing this when you try any of the above code?
